# Generated by Django 2.2 on 2020-03-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Body',
            new_name='Description',
        ),
    ]
