# Generated by Django 2.2 on 2020-02-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
